# fly.toml app configuration file generated for reddit-time-warp-server on 2025-09-24T03:32:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reddit-time-warp-server'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  HOST = '0.0.0.0'
  PORT = '8000'
  RELOAD = 'false'
  TORRENT_URL = 'https://academictorrents.com/download/1614740ac8c94505e4ecb9d88be8bed7b6afddd4.torrent'
  TORRENT_SUBREDDITS_PATH = 'subreddits24'
  TORRENT_CACHE_DIR = '.torrent_cache'
  SUBREDDIT_CACHE_DIR = '.subreddit_cache'
  SUBREDDIT_CACHE_MAX_SIZE_BYTES = '4gb'
  MAX_SUBREDDIT_SIZE_BYTES = '250mb'
  CORS_ALLOWED_ORIGINS = '*'